### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by kimkyunghun3** [kimkyunghun3/ios-bank-manager#16]
- [x] 고객 10명 추가 버튼 누르면 대기중에 10명 추가
- [x] 초기화 버튼 누르면 타이머, 고객 모두 초기화
- [x] 타이머 구현
- [x] 업무 시작 시, 대기중 -> 업무중 이동 
- [x] 업무 종료 시, 업무중에서 삭제
- [x] 모든 고객 업무가 종료되면 타이머 정지
